################
### DEFAULTS ###
################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$browser = zen-browser
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
