#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    repeat_rate = 50
    repeat_delay = 300

    follow_mouse = 1
    numlock_by_default = true
    left_handed = false
    float_switch_override_focus = false

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.+
    touchpad {
        disable_while_typing = true
        natural_scroll = true
        clickfinger_behavior = false
        middle_button_emulation = false
        tap-to-click = true
        drag_lock = false
    }
}
