################
### SETTINGS ###
################

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    disable_splash_rendering = false
    disable_hyprland_logo = false
    vrr = 1

    mouse_move_enables_dpms = true

    enable_swallow = off
    swallow_regex = ^(kitty)$

    initial_workspace_tracking = 0
    middle_click_paste = false
}

# https://wiki.hypr.land/Configuring/Variables/#binds
binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

# https://wiki.hypr.land/Configuring/Variables/#xwayland
xwayland {
  enabled = true
  force_zero_scaling = true
}

# https://wiki.hypr.land/Configuring/Variables/#cursor
cursor {
  hide_on_key_press = true
}
