####################
### Window Rules ###
####################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
  name = windowrule-1
  opacity = 0.85 override 0.7 override
  suppress_event = maximize
  match:class = .*
}


# windowrule to avoid idle for fullscreen apps
windowrule {
  name = windowrule-2
  idle_inhibit = fullscreen
  match:fullscreen = 1
}


# windowrule - ######### float popups and dialogue #######
windowrule {
  name = windowrule-3
  float = on
  center = on
  match:title = ^(Authentication Required)$
}


windowrule {
  name = windowrule-4
  float = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  center = on
  match:title = ^(Add Folder to Workspace)$
}


windowrule {
  name = windowrule-5
  float = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  center = on
  match:title = ^(Save As)$
}


windowrule {
  name = windowrule-6
  float = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  match:initial_title = (Open Files)
}


windowrule {
  name = windowrule-7
  float = on
  size = (monitor_w*0.6) (monitor_h*0.6)
  stay_focused = on
  match:class = (tui)
}

# END of float popups and dialogue #######

# Picture-in-Picture
windowrule {
  name = windowrule-8
  opacity = 0.5 0.8
  float = on
  pin = on
#  move = 1400 900
  move = monitor_w-500 monitor_h-300
  keep_aspect_ratio = on
  match:title = ^(Picture-in-Picture)$
}


# Blur Rofi
layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0.5
  match:namespace = rofi
}


# Blur Waybar
layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0.5
  match:namespace = waybar
}


# Blur SwayNC
layerrule {
  name = layerrule-3
  blur = on
  ignore_alpha = 0.5
  match:namespace = swaync-control-center
}

layerrule {
  name = layerrule-4
  blur = on
  ignore_alpha = 0.5
  match:namespace = swaync-notification-window
}


# Ignore maximize requests from apps. You'll probably like this.

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-9
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}
