color0 #424751
color1 #ffb4ab
color2 #a4c9ff
color3 #b3c8e9
color4 #f0b0ff
color5 #a4c9ff
color6 #b3c8e9
color7 #e1e2e9
color8 #8c919c
color9 #ffb4ab
color10 #a4c9ff
color11 #b3c8e9
color12 #f0b0ff
color13 #a4c9ff
color14 #b3c8e9
color15 #e1e2e9

cursor                #e1e2e9
cursor_text_color     #111318
background            #111318
foreground            #e1e2e9
selection_foreground  #c2c6d2
selection_background  #424751
active_border_color   #a4c9ff
inactive_border_color #424751
url_color             #a4c9ff

active_tab_foreground   #00315d
active_tab_background   #a4c9ff
inactive_tab_foreground #c2c6d2
inactive_tab_background #424751
cursor_trail_color      #c2c6d2
