<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
<* endfor *>
$font_family = Google Sans Flex Freeze Bold
$font_family_clock = Google Sans Flex Freeze Bold
$font_material_symbols = Material Symbols Rounded

$background_image = {{image}}